-- =============================================================
-- MATT'S WORLD - AKTUALIZACJA CMS V2 (HYBRYDA + BACKUPY)
-- TEN PLIK jest przeznaczony dla sytuacji, gdy CMS_SETUP.sql
-- z poprzedniej wersji został już wcześniej uruchomiony.
-- Supabase -> SQL Editor -> New query -> wklej całość -> Run
-- =============================================================

-- Funkcja administratora (bezpiecznie nadpisujemy obecną definicję).
create or replace function public.matt_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.email = (auth.jwt() ->> 'email')
      and p.role = 'admin'
  );
$$;
revoke all on function public.matt_is_admin() from public;
grant execute on function public.matt_is_admin() to authenticated;

-- Upewniamy się, że zapisy CMS i eventów są admin-only.
alter table public.cms_data enable row level security;
drop policy if exists "cms admin insert" on public.cms_data;
create policy "cms admin insert" on public.cms_data for insert to authenticated with check (public.matt_is_admin());
drop policy if exists "cms admin update" on public.cms_data;
create policy "cms admin update" on public.cms_data for update to authenticated using (public.matt_is_admin()) with check (public.matt_is_admin());
drop policy if exists "cms admin delete" on public.cms_data;
create policy "cms admin delete" on public.cms_data for delete to authenticated using (public.matt_is_admin());

alter table public.events enable row level security;
drop policy if exists "admin insert events" on public.events;
create policy "admin insert events" on public.events for insert to authenticated with check (public.matt_is_admin());
drop policy if exists "admin update events" on public.events;
create policy "admin update events" on public.events for update to authenticated using (public.matt_is_admin()) with check (public.matt_is_admin());
drop policy if exists "admin delete events" on public.events;
create policy "admin delete events" on public.events for delete to authenticated using (public.matt_is_admin());

create table if not exists public.cms_backups (
  id bigint generated by default as identity primary key,
  label text not null default 'Backup ręczny',
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  created_by text
);
alter table public.cms_backups enable row level security;
revoke all on table public.cms_backups from anon;
revoke insert, update, delete on table public.cms_backups from authenticated;
grant select on table public.cms_backups to authenticated;
drop policy if exists "cms backups admin read" on public.cms_backups;
create policy "cms backups admin read" on public.cms_backups for select to authenticated using (public.matt_is_admin());

create or replace function public.matt_build_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare result jsonb;
begin
  if not public.matt_is_admin() then raise exception 'Brak uprawnień administratora'; end if;
  select jsonb_build_object(
    'format', 'matts-world-backup-v1',
    'created_at', now(),
    'cms_data', coalesce((select jsonb_agg(to_jsonb(c) order by c.key) from public.cms_data c), '[]'::jsonb),
    'events', coalesce((select jsonb_agg(to_jsonb(e)) from public.events e), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;
revoke all on function public.matt_build_snapshot() from public;
grant execute on function public.matt_build_snapshot() to authenticated;

create or replace function public.matt_create_backup(p_label text default 'Backup ręczny')
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare new_id bigint;
begin
  if not public.matt_is_admin() then raise exception 'Brak uprawnień administratora'; end if;
  insert into public.cms_backups(label, snapshot, created_by)
  values (coalesce(nullif(trim(p_label), ''), 'Backup ręczny'), public.matt_build_snapshot(), auth.jwt() ->> 'email')
  returning id into new_id;
  return new_id;
end;
$$;
revoke all on function public.matt_create_backup(text) from public;
grant execute on function public.matt_create_backup(text) to authenticated;

create or replace function public.matt_restore_snapshot(p_snapshot jsonb, p_label text default 'Przywrócenie z pliku')
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare safety_backup_id bigint;
begin
  if not public.matt_is_admin() then raise exception 'Brak uprawnień administratora'; end if;
  if p_snapshot is null
     or jsonb_typeof(p_snapshot) <> 'object'
     or jsonb_typeof(coalesce(p_snapshot->'cms_data', '[]'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_snapshot->'events', '[]'::jsonb)) <> 'array' then
    raise exception 'Nieprawidłowy format pliku backupu';
  end if;

  safety_backup_id := public.matt_create_backup('AUTO: przed przywróceniem — ' || coalesce(nullif(trim(p_label), ''), 'backup'));
  delete from public.cms_data;
  delete from public.events;

  insert into public.cms_data(key, data, updated_at)
  select x.key, coalesce(x.data, '{}'::jsonb), coalesce(x.updated_at, now())
  from jsonb_to_recordset(coalesce(p_snapshot->'cms_data', '[]'::jsonb))
       as x(key text, data jsonb, updated_at timestamptz)
  where x.key is not null;

  insert into public.events
  select * from jsonb_populate_recordset(null::public.events, coalesce(p_snapshot->'events', '[]'::jsonb));

  return safety_backup_id;
end;
$$;
revoke all on function public.matt_restore_snapshot(jsonb, text) from public;
grant execute on function public.matt_restore_snapshot(jsonb, text) to authenticated;

create or replace function public.matt_restore_backup(p_backup_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare snap jsonb; backup_label text;
begin
  if not public.matt_is_admin() then raise exception 'Brak uprawnień administratora'; end if;
  select b.snapshot, b.label into snap, backup_label from public.cms_backups b where b.id = p_backup_id;
  if snap is null then raise exception 'Nie znaleziono backupu o ID %', p_backup_id; end if;
  return public.matt_restore_snapshot(snap, 'backup #' || p_backup_id || ' — ' || coalesce(backup_label, 'bez nazwy'));
end;
$$;
revoke all on function public.matt_restore_backup(bigint) from public;
grant execute on function public.matt_restore_backup(bigint) to authenticated;
